/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE FLIGHT_INFORMATION PACKING
package com.MAVLink.common;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;
import com.MAVLink.Messages.Description;

/**
 * Flight information.
        This includes time since boot for arm, takeoff, and land, and a flight number.
        Takeoff and landing values reset to zero on arm.
        This can be requested using MAV_CMD_REQUEST_MESSAGE.
        Note, some fields are misnamed - timestamps are from boot (not UTC) and the flight_uuid is a sequence number.
      
 */
public class msg_flight_information extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_FLIGHT_INFORMATION = 264;
    public static final int MAVLINK_MSG_LENGTH = 32;
    private static final long serialVersionUID = MAVLINK_MSG_ID_FLIGHT_INFORMATION;

    
    /**
     * Timestamp at arming (since system boot). Set to 0 on boot. Set value on arming. Note, field is misnamed UTC.
     */
    @Description("Timestamp at arming (since system boot). Set to 0 on boot. Set value on arming. Note, field is misnamed UTC.")
    @Units("us")
    public long arming_time_utc;
    
    /**
     * Timestamp at takeoff (since system boot). Set to 0 at boot and on arming. Note, field is misnamed UTC.
     */
    @Description("Timestamp at takeoff (since system boot). Set to 0 at boot and on arming. Note, field is misnamed UTC.")
    @Units("us")
    public long takeoff_time_utc;
    
    /**
     * Flight number. Note, field is misnamed UUID.
     */
    @Description("Flight number. Note, field is misnamed UUID.")
    @Units("")
    public long flight_uuid;
    
    /**
     * Timestamp (time since system boot).
     */
    @Description("Timestamp (time since system boot).")
    @Units("ms")
    public long time_boot_ms;
    
    /**
     * Timestamp at landing (in ms since system boot). Set to 0 at boot and on arming.
     */
    @Description("Timestamp at landing (in ms since system boot). Set to 0 at boot and on arming.")
    @Units("ms")
    public long landing_time;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_FLIGHT_INFORMATION;

        packet.payload.putUnsignedLong(arming_time_utc);
        packet.payload.putUnsignedLong(takeoff_time_utc);
        packet.payload.putUnsignedLong(flight_uuid);
        packet.payload.putUnsignedInt(time_boot_ms);
        
        if (isMavlink2) {
             packet.payload.putUnsignedInt(landing_time);
            
        }
        return packet;
    }

    /**
     * Decode a flight_information message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.arming_time_utc = payload.getUnsignedLong();
        this.takeoff_time_utc = payload.getUnsignedLong();
        this.flight_uuid = payload.getUnsignedLong();
        this.time_boot_ms = payload.getUnsignedInt();
        
        if (isMavlink2) {
             this.landing_time = payload.getUnsignedInt();
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_flight_information() {
        this.msgid = MAVLINK_MSG_ID_FLIGHT_INFORMATION;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_flight_information( long arming_time_utc, long takeoff_time_utc, long flight_uuid, long time_boot_ms, long landing_time) {
        this.msgid = MAVLINK_MSG_ID_FLIGHT_INFORMATION;

        this.arming_time_utc = arming_time_utc;
        this.takeoff_time_utc = takeoff_time_utc;
        this.flight_uuid = flight_uuid;
        this.time_boot_ms = time_boot_ms;
        this.landing_time = landing_time;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_flight_information( long arming_time_utc, long takeoff_time_utc, long flight_uuid, long time_boot_ms, long landing_time, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_FLIGHT_INFORMATION;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.arming_time_utc = arming_time_utc;
        this.takeoff_time_utc = takeoff_time_utc;
        this.flight_uuid = flight_uuid;
        this.time_boot_ms = time_boot_ms;
        this.landing_time = landing_time;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_flight_information(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_FLIGHT_INFORMATION;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_FLIGHT_INFORMATION - sysid:"+sysid+" compid:"+compid+" arming_time_utc:"+arming_time_utc+" takeoff_time_utc:"+takeoff_time_utc+" flight_uuid:"+flight_uuid+" time_boot_ms:"+time_boot_ms+" landing_time:"+landing_time+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_FLIGHT_INFORMATION";
    }
}
        