/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Camera sources for MAV_CMD_SET_CAMERA_SOURCE
 */
public class CAMERA_SOURCE {
   public static final int CAMERA_SOURCE_DEFAULT = 0; /* Default camera source. | */
   public static final int CAMERA_SOURCE_RGB = 1; /* RGB camera source. | */
   public static final int CAMERA_SOURCE_IR = 2; /* IR camera source. | */
   public static final int CAMERA_SOURCE_NDVI = 3; /* NDVI camera source. | */
   public static final int CAMERA_SOURCE_ENUM_END = 4; /*  | */
}