/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
 */
public class FENCE_TYPE {
   public static final int FENCE_TYPE_ALL = 0; /* All fence types | */
   public static final int FENCE_TYPE_ALT_MAX = 1; /* Maximum altitude fence | */
   public static final int FENCE_TYPE_CIRCLE = 2; /* Circle fence | */
   public static final int FENCE_TYPE_POLYGON = 4; /* Polygon fence | */
   public static final int FENCE_TYPE_ALT_MIN = 8; /* Minimum altitude fence | */
   public static final int FENCE_TYPE_ENUM_END = 9; /*  | */
}