/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Illuminator module error flags (bitmap, 0 means no error)
 */
public class ILLUMINATOR_ERROR_FLAGS {
   public static final int ILLUMINATOR_ERROR_FLAGS_THERMAL_THROTTLING = 1; /* Illuminator thermal throttling error. | */
   public static final int ILLUMINATOR_ERROR_FLAGS_OVER_TEMPERATURE_SHUTDOWN = 2; /* Illuminator over temperature shutdown error. | */
   public static final int ILLUMINATOR_ERROR_FLAGS_THERMISTOR_FAILURE = 4; /* Illuminator thermistor failure. | */
   public static final int ILLUMINATOR_ERROR_FLAGS_ENUM_END = 5; /*  | */
}