/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Modes of illuminator
 */
public class ILLUMINATOR_MODE {
   public static final int ILLUMINATOR_MODE_UNKNOWN = 0; /* Illuminator mode is not specified/unknown | */
   public static final int ILLUMINATOR_MODE_INTERNAL_CONTROL = 1; /* Illuminator behavior is controlled by MAV_CMD_DO_ILLUMINATOR_CONFIGURE settings | */
   public static final int ILLUMINATOR_MODE_EXTERNAL_SYNC = 2; /* Illuminator behavior is controlled by external factors: e.g. an external hardware signal | */
   public static final int ILLUMINATOR_MODE_ENUM_END = 3; /*  | */
}