/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * 
	Possible safety switch states.
      
 */
public class SAFETY_SWITCH_STATE {
   public static final int SAFETY_SWITCH_STATE_SAFE = 0; /* Safety switch is engaged and vehicle should be safe to approach. | */
   public static final int SAFETY_SWITCH_STATE_DANGEROUS = 1; /* Safety switch is NOT engaged and motors, propellers and other actuators should be considered active. | */
   public static final int SAFETY_SWITCH_STATE_ENUM_END = 2; /*  | */
}